# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Agent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41gent.proto\" \n\x05World\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x1e\n\x03NPC\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x1f\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x18\n\x08Position\x12\x0c\n\x04name\x18\x01 \x01(\t\"M\n\x05\x45vent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1c\n\x06status\x18\x02 \x01(\x0e\x32\x0c.EventStatus\x12\x18\n\x04type\x18\x03 \x01(\x0e\x32\n.EventType\"\'\n\x05Order\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\"\xc0\x01\n\nAgentQuery\x12\x15\n\x05world\x18\x01 \x01(\x0b\x32\x06.World\x12\x1b\n\x08position\x18\x02 \x01(\x0b\x32\t.Position\x12\x17\n\tsourceNPC\x18\x03 \x01(\x0b\x32\x04.NPC\x12\x15\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x06.Event\x12\x19\n\x0binteractNPC\x18\x05 \x01(\x0b\x32\x04.NPC\x12\x1c\n\rinteractItems\x18\x06 \x03(\x0b\x32\x05.Item\x12\x15\n\x05order\x18\x07 \x01(\x0b\x32\x06.Order\"u\n\nAgentReply\x12\x15\n\x05world\x18\x01 \x01(\x0b\x32\x06.World\x12\x1b\n\x08position\x18\x02 \x01(\x0b\x32\t.Position\x12\x15\n\x05order\x18\x03 \x01(\x0b\x32\x06.Order\x12\x1c\n\rinteractItems\x18\x04 \x03(\x0b\x32\x05.Item*,\n\x0b\x45ventStatus\x12\t\n\x05START\x10\x00\x12\t\n\x05\x44OING\x10\x01\x12\x07\n\x03\x45ND\x10\x02* \n\tEventType\x12\x08\n\x04\x43HAT\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Agent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTSTATUS._serialized_start=574
  _EVENTSTATUS._serialized_end=618
  _EVENTTYPE._serialized_start=620
  _EVENTTYPE._serialized_end=652
  _WORLD._serialized_start=15
  _WORLD._serialized_end=47
  _NPC._serialized_start=49
  _NPC._serialized_end=79
  _ITEM._serialized_start=81
  _ITEM._serialized_end=112
  _POSITION._serialized_start=114
  _POSITION._serialized_end=138
  _EVENT._serialized_start=140
  _EVENT._serialized_end=217
  _ORDER._serialized_start=219
  _ORDER._serialized_end=258
  _AGENTQUERY._serialized_start=261
  _AGENTQUERY._serialized_end=453
  _AGENTREPLY._serialized_start=455
  _AGENTREPLY._serialized_end=572
# @@protoc_insertion_point(module_scope)
