# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent2.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import world_pb2 as world__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61gent2.proto\x12\x0c\x61igame.agent\x1a\x0bworld.proto\x1a\x19google/protobuf/any.proto\" \n\x05World\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\x03\"\x1e\n\x03NPC\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\x03\"\x1f\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\x03\"g\n\x05\x45vent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12)\n\x06status\x18\x02 \x01(\x0e\x32\x19.aigame.agent.EventStatus\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.aigame.agent.EventType\"\x93\x01\n\x0b\x43ommonOrder\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x37\n\x10\x64\x65stination_type\x18\x03 \x01(\x0e\x32\x1d.aigame.agent.DestinationType\x12)\n\x0b\x64\x65stination\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\"g\n\tChatOrder\x12!\n\x06target\x18\x01 \x01(\x0b\x32\x11.aigame.agent.NPC\x12\x0c\n\x04text\x18\x02 \x01(\t\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.aigame.agent.EventStatus\"\x80\x01\n\x0f\x41gentEventQuery\x12\x11\n\tworld_key\x18\x01 \x01(\x03\x12\x0f\n\x07npc_key\x18\x02 \x01(\x03\x12%\n\x04\x61rea\x18\x03 \x01(\x0b\x32\x17.aigame.world.WorldArea\x12\"\n\x05\x65vent\x18\x04 \x03(\x0b\x32\x13.aigame.agent.Event\"\xae\x01\n\x0f\x41gentOrderReply\x12\x11\n\tworld_key\x18\x01 \x01(\x03\x12%\n\x04\x61rea\x18\x02 \x01(\x0b\x32\x17.aigame.world.WorldArea\x12\x0f\n\x07npc_key\x18\x03 \x01(\x03\x12+\n\norder_type\x18\x04 \x01(\x0e\x32\x17.aigame.agent.EventType\x12#\n\x05order\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any*,\n\x0b\x45ventStatus\x12\t\n\x05\x44OING\x10\x00\x12\t\n\x05START\x10\x01\x12\x07\n\x03\x45ND\x10\x02*!\n\tEventType\x12\n\n\x06\x43OMMON\x10\x00\x12\x08\n\x04\x43HAT\x10\x01*=\n\x0f\x44\x65stinationType\x12\r\n\tTYPE_AREA\x10\x00\x12\r\n\tTYPE_ITEM\x10\x01\x12\x0c\n\x08TYPE_NPC\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EVENTSTATUS']._serialized_start=837
  _globals['_EVENTSTATUS']._serialized_end=881
  _globals['_EVENTTYPE']._serialized_start=883
  _globals['_EVENTTYPE']._serialized_end=916
  _globals['_DESTINATIONTYPE']._serialized_start=918
  _globals['_DESTINATIONTYPE']._serialized_end=979
  _globals['_WORLD']._serialized_start=70
  _globals['_WORLD']._serialized_end=102
  _globals['_NPC']._serialized_start=104
  _globals['_NPC']._serialized_end=134
  _globals['_ITEM']._serialized_start=136
  _globals['_ITEM']._serialized_end=167
  _globals['_EVENT']._serialized_start=169
  _globals['_EVENT']._serialized_end=272
  _globals['_COMMONORDER']._serialized_start=275
  _globals['_COMMONORDER']._serialized_end=422
  _globals['_CHATORDER']._serialized_start=424
  _globals['_CHATORDER']._serialized_end=527
  _globals['_AGENTEVENTQUERY']._serialized_start=530
  _globals['_AGENTEVENTQUERY']._serialized_end=658
  _globals['_AGENTORDERREPLY']._serialized_start=661
  _globals['_AGENTORDERREPLY']._serialized_end=835
# @@protoc_insertion_point(module_scope)
